import type { Metadata } from "next";
import { Bangers, Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";
import ActionButton from "@/components/action-button";

const bangers = Bangers({
	subsets: ["latin"],
	weight: ["400"],
	variable: "--font-bangers",
});

const beVietnamPro = Be_Vietnam_Pro({
	subsets: ["latin"],
	weight: ["400", "500", "600", "700", "800", "900"],
	variable: "--font-be-vietnam-pro",
	display: "swap",
});

export const metadata: Metadata = {
	title: "HCM202 Project",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="dark">
			<body
				className={`${bangers.variable} ${beVietnamPro.variable} antialiased font-bevietnampro`}
			>
				{children}
				<ActionButton />
				{/* eslint-disable-next-line @next/next/no-sync-scripts */}
				<script src="https://cdn.botpress.cloud/webchat/v3.3/inject.js"></script>
				<script
					src="https://files.bpcontent.cloud/2025/09/15/03/20250915030247-R30TMPXR.js"
					defer
				></script>
			</body>
		</html>
	);
}
